### ISSUE TITLE
[DOCKER] Waiting on storage to start

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [pandora-analysis/pandora#122]
Hello,

i have tried to get Pandora running using the docker-compose file. The build process has worked so far, the required containers are available. However, **I cannot reach the pandora website**. In the logs I find the note "Waiting on storage to start" in a endless loop.

Here are some screenshots for the container status:
**Overview**
![image](https://user-images.githubusercontent.com/50357205/198231434-28abe588-18f2-4072-b30e-1513c2094b9f.png)

**Redis**
![image](https://user-images.githubusercontent.com/50357205/198231644-ed87407c-3346-4abf-bcb5-2006a14c857c.png)

**Pandora**
![image](https://user-images.githubusercontent.com/50357205/198231767-16c80328-d54e-4354-984a-721b1666dd7f.png)

**kvrocks**
![image](https://user-images.githubusercontent.com/50357205/198232155-71dfd775-3dd5-4344-adca-d8b8cbc45d28.png)

**ClamAV**
![image](https://user-images.githubusercontent.com/50357205/198232688-464c04ed-c607-448b-a1ab-db55d09dca3a.png)

Is there anything i can provide for debugging or testing ?
Thank you very much.

**Comment by Rafiot** [comment]
I have no idea how docker works, but this message is because the start script cannot reach kvrocks. Can the containers talk to each other via the network? Based on the message, I'd guess the pandora container cannot connect to the kvrocks one.

**Comment by ITSEC-DACHSER** [comment]
Hi Rafiot,

thanks for your feedback. The Container was connected to two networks. I removed the second network connection which I had added before. Now all containers are in the same network with only one network connection. 

Sadly ,the error still persists. How does Pandora find the kvrock service on the other IP ?

Current setup, all container in one network:
![image](https://user-images.githubusercontent.com/50357205/198259279-7a3a9e74-ae3e-4bab-93cb-eba79792b349.png)

Is there a way for me to debug or provide some more logs ?

**Comment by Rafiot** [comment]
ok, I think it will be an easy fix: It gets the IP from the config file: https://github.com/pandora-analysis/pandora/blob/main/config/generic.json.sample#L7

So it's going to be in `/config/generic.json`  -> storage_db_hostname -> set the IP if the container

**Comment by ITSEC-DACHSER** [comment]
Yes, it was that easy fix! pandora is up and running.

Thanks for that hint.

**Comment by Rafiot** [comment]
\o/ let me know if you have any further questions!
