### ISSUE TITLE
[enhancement] Send message to xxx

### ISSUE THREAD

**Issue by kurgans0** [pandora-analysis/pandora#153]
On file .\website\web\templates\analysis.html, is it possible to replace "Send message to xxx" (line 621) by an entry in a config file (maybe .\config\generic.json.sample)
Goal > custom Pandora with the local IT support (all company don't have a CERT ;-)

**Comment by kurgans0** [comment]
In the same context, the possibility to customize "Alert Administrator" (line 90)

**Comment by Rafiot** [comment]
Does that solution work for you? It is a bit dirty, but should work okay.

**Comment by kurgans0** [comment]
I confirme > deployed and working in Prod.

**Comment by Rafiot** [comment]
Great!
