### ISSUE TITLE
Overall Result issue

### ISSUE THREAD

**Issue by kurgans0** [pandora-analysis/pandora#165]
When we drag-and-drop many files, the "Overall Result" display the status of the last file.

But if there is a virus in a file (not the last file), the "Overall Result" will "clean" status (based on the last file).
It's confusing for the users. No?

**Comment by Rafiot** [comment]
So... I didn't realized you can drag-and-drop many files at once... Let's make it a TODO because as of now, it definitely has an undefined outcome.

**Comment by Rafiot** [comment]
This change disables multi-file upload. This is the temporary fix until I figure out a better solution: https://github.com/pandora-analysis/pandora/commit/150618ba8a366140b1c403f75eefdc622b327c81 

For now, if you have multiple files, zip them first and let pandora extract them. I'm closing this issue and leaving the other one open until we implement a more long term solution.
