### ISSUE TITLE
Textract package installation is failing in poetry install step (Python 3.10.6 environment)

### ISSUE THREAD

**Issue by PersonalizedFinances** [pandora-analysis/pandora#189]
Installing textract (1.6.5 2d320fc): Failed

  CalledProcessError

  Command '['/home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10', '--upgrade', '--no-deps', '/home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10/src/textract']' returned non-zero exit status 1.

  at /usr/lib/python3.10/subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│
       528│

The following error occurred when trying to handle this error:

  EnvCommandError

  Command ['/home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10', '--upgrade', '--no-deps', '/home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10/src/textract'] errored with the following return code 1, and output:
  Processing /home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10/src/textract
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [3 lines of output]
        error in textract setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
            chardet>=4.*
                   ~~~^
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.


  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│
      1542│         return decode(output)
      1543│
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10/src/textract

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:58 in pip_install
       54│
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│

**Comment by Rafiot** [comment]
This is an odd error, because the install works fine on my machine (3.10.7) and on github actions. And I cannot reproduce it. 

It looks like a typo in the package you're installing has a typo or something? Are you installing pandora with `poetry install`? Try something like `poetry install --sync`, maybe?

**Comment by PersonalizedFinances** [comment]
Yes. I am installing via poetry install according to the instructions.

I am installing on Ubuntu 22.04.1 LTS machine. I tried with again with poetry install --sync and I am getting the same error.

I can try to update python version. Which OS is recommended for installation?

**Comment by Rafiot** [comment]
It should absolutely work on Ubuntu 22.04.1 LTS, this is definitely a bug. The problem is that I'm not sure what is causing it. It sounds like a cache related issue, maybe?

Try running `poetry run pip install chardet` from the directory you cloned pandora into and see if it works. The odd thing is that the `textract` package seems to be trying to install chardet 4 when it should be trying to install chardet 5.

**Comment by PersonalizedFinances** [comment]
Thank you Raphael. Now it works.
