### ISSUE TITLE
MISP export should have been in an Event dict

### ISSUE THREAD

**Issue by adulau** [pandora-analysis/pandora#216]
If you export a pandora analysis as MISP event, it can be imported per se in MISP as it's missing the Event dict around. The rest of the event is correct.

**Comment by Rafiot** [comment]
hmmm it was working at some point in the past, the Event wrapper was not required afaik.

**Comment by adulau** [comment]
Fixed in MISP https://github.com/MISP/MISP/commit/edfdc5bfa2efd3865d56d69e889957405452548c
