### ISSUE TITLE
clean task folder

### ISSUE THREAD

**Issue by dbarzin** [pandora-analysis/pandora#233]
After using Pandora, the folder pandora/tasks contains remaining files that takes a lot of place.
Is is possible to remove these files automatically ?

**Comment by Rafiot** [comment]
You can click on delete on the recent page, but there is no other easy way to do that. 

You're right, is would be nice to have a way to archive (or delete) the old files in bulk. Turning this issue into a TODO.

**Comment by info-sic** [comment]
Is it safe to delete files in the taskfolder manually or does this lead to db-inconsitsencies?

**Comment by Rafiot** [comment]
It is safe, the database will recover fine.

But there is now a file to do that (based on a date): `tools/delete_old_files.py`, and it can be put in a cron for automation if needed.
