### ISSUE TITLE
Issue related to uploading files

### ISSUE THREAD

**Issue by doclemin** [pandora-analysis/pandora#280]
Hello,

I'm encountering an issue with file uploads in my on-premise environment. After uploading a file, the interface displays the file, but the progress bar remains frozen and does not show any progress. The last exemple i have is a regular PDF file. Interestingly, when I tested the same file on a demo platform, it worked perfectly without any issues.

Do you have any idea why this issue is happening in the on-premise environment? I would greatly appreciate your assistance. 

Thank you in advance for your help.
![2023-05-04_17h25_20](https://user-images.githubusercontent.com/49001878/236254933-f9432c20-1616-4910-898a-809d856e81b1.png)

**Comment by Rafiot** [comment]
I do not have the slightest idea what could be causing that. Can you open the dev tools of your browser and check if there is anything there? That sounds like something going poorly in the JS code but nothing obvious from the screenshot.

**Comment by doclemin** [comment]
I no longer have the issue. I didn't do anything special, but it resolved itself! 
Thank you for your response.
