### ISSUE TITLE
[Worker] Normalisation des Classes des workers

### ISSUE THREAD

**Issue by FafnerKeyZee** [pandora-analysis/pandora#29]
Il faudra normaliser les classes pour les workers et surtout synchroniser les noms des classes pour l'affichage:
![image](https://user-images.githubusercontent.com/11160904/154925038-6350b03e-9eb7-45cc-9e0d-e7304e6cc270.png)

**Comment by adulau** [comment]
I think the best would be to have a "display name" variable per worker to be the name displayed on the UI and the internal name remains. @Rafiot what do you think?

**Comment by Rafiot** [comment]
Right now, we use the module name (the filename) as ID, which works but isn't amazing. Initially, the plan was to add variables in the worker classes, but as you said, we could also use the same technique as the misp-modules: https://github.com/MISP/misp-modules/blob/main/documentation/website/expansion/hashlookup.json
