### ISSUE TITLE
Kvrock failed to start in Docker compose

### ISSUE THREAD

**Issue by samuelmonsempessenthorus** [pandora-analysis/pandora#429]
**Version:**
Latest

**Step to reproduce:**
git clone https://github.com/pandora-analysis/pandora.git
cd pandora
cp ./config/generic.json.sample ./config/generic.json
sudo docker compose up

**Issue:**
pandora-kvrocks-1  | Failed to load config, err: at line: #L606, err: value shoud between 0 and 32

**Comment by Rafiot** [comment]
Can you give it another shot? The docker for kvrocks moved to apache and I guess it is pulling an old one.
