### ISSUE TITLE
[Question] How do workers work?

### ISSUE THREAD

**Issue by hyprem** [pandora-analysis/pandora#574]
Hi all

I am just wondering how and if It is needed to enable additional workers from the github repo directory 
https://github.com/pandora-analysis/pandora/tree/main/pandora/workers

Do I need to rename the yml.sample to .yml or does it need the content of the yml.sample in the config/generic.yml file?

**Comment by info-sic** [comment]
Rename .yml.sample to .yml and provide information in there, if nessecary, like an API-key
