### ISSUE TITLE
Improving disclaimer

### ISSUE THREAD

**Issue by Rafiot** [pandora-analysis/pandora#67]
We currently have 2 disclaimers.

1. default disclaimer: always displayed
2. special disclaimer: (optional) used for special use cases to alert users on exceptional circumstances when there are files that are known to bypass pandora in some ways and there are no fixes yet.

Problem: alarm fatigue and people do not read the messages if they're always there.

Possible solutions:

1. Only display the disclaimer if a used wants to see it (click on a button -> show the disclaimer). Problem: Why would anyone do that? 
2. Require the users to click on a button to accept the disclaimer before being able to submit a file. Problem: Super annoying for power users.
3. Require the users to accept the disclaimer once per session, and never again until the session expires. Problem: the session expires every 10 hours so a poweruser will need to click on the button at least once a day, this is annoying.

The 3rd solution is probably the least bad, especially if we allow to increase the expiration time.

**Comment by FafnerKeyZee** [comment]
An other solution:

4. Move the disclair on the bottom of the page, with a smaller font and without any background color.

**Comment by Rafiot** [comment]
We went with 4 for now.
