### ISSUE TITLE
[Enhancemet] Scripts from PDFs as obervables

### ISSUE THREAD

**Issue by info-sic** [pandora-analysis/pandora#686]
What a pity I can't code securely. Otherwise I'd give integrating something like `pdfinfo -js ` a try.  Getting active content in PDF as an observable would be nice to have.
Sincerely 
Manu

**Comment by Rafiot** [comment]
I'll see what I can do.

**Comment by Rafiot** [comment]
I totally forgot about it, but this module might (partially) solve the issue: https://github.com/pandora-analysis/pandora/commit/92cd0903663a929475c27164e91e2c0edda5d258
