### ISSUE TITLE
Start Pandora at boot

### ISSUE THREAD

**Issue by dbarzin** [pandora-analysis/pandora#81]
How do you get Pandora to start at boot time ?
Could you share a startup script ?
Thanks,
Didier

**Comment by Rafiot** [comment]
You can use the systemd script: https://github.com/pandora-analysis/pandora/tree/main/etc/systemd/system 

I'm not using it right now, but the configuration will be very similar to the one of lookyloo: https://www.lookyloo.eu/docs/main/install-lookyloo-production.html#_systemd_service

**Comment by dbarzin** [comment]
There is not script in https://github.com/pandora-analysis/pandora/tree/main/etc/systemd/system

**Comment by dbarzin** [comment]
Thanks for the info !
