### ISSUE TITLE
File text preview

### ISSUE THREAD

**Issue by jhautefeuille** [pandora-analysis/pandora#92]
When I submit a text file, in details preview, I've : 

Unable to generate preview: Connector : couldn't connect to socket (Connection refused) ./io/source/connector/connector.cxx:117

**Comment by Rafiot** [comment]
Which version of libreoffice are you using? It is generally a problem if you use the default version from the packages, and is (generally?) solved in the version from the PPAs.

**Comment by jhautefeuille** [comment]
I'm using the PPA version 

`drsi@pandora:/etc/apt/sources.list.d$ ls
libreoffice-ubuntu-ppa-jammy.list
drsi@pandora:/etc/apt/sources.list.d$ cat libreoffice-ubuntu-ppa-jammy.list 
deb https://ppa.launchpadcontent.net/libreoffice/ppa/ubuntu/ jammy main
# deb-src https://ppa.launchpadcontent.net/libreoffice/ppa/ubuntu/ jammy main
drsi@pandora:/etc/apt/sources.list.d$ apt-cache policy libreoffice
libreoffice:
  Installé : 1:7.3.5-0ubuntu0.22.04.1
  Candidat : 1:7.3.5-0ubuntu0.22.04.1
 Table de version :
 *** 1:7.3.5-0ubuntu0.22.04.1 500
        500 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages
        500 https://ppa.launchpadcontent.net/libreoffice/ppa/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1:7.3.2-0ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
`

**Comment by Rafiot** [comment]
Right, thanks for the update. The interaction with libreoffice is a bit weird and I'm not totally sure which condition leads to a broken preview generation.
